apiVersion: v1
description: IBM MQ queue manager
icon: https://developer.ibm.com/messaging/wp-content/uploads/sites/18/2018/03/ibm_mq_32.png
name: ibm-mqadvanced-server-ams
tillerVersion: '>=2.4.0'
version: 1.3.0
