license:
  __metadata:
    label: "License"
    type: "string"
    required: true
    options:
    - label: "Accepted"
      value: "accept"
    - label: "Not accepted"
      value: "not accepted"

image:
  __metadata:
    label: "Image"
  repository:
    __metadata:
      label: "Image repository"
      description: "Docker image location"
      type: "string"
      immutable: false
      required: true
  tag:
    __metadata:
      label: "Image tag"
      description: "Docker image tag"
      type: "string"
      immutable: false
      required: true
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Image pull policy"
      description: "Always, Never, or IfNotPresent. Defaults to Always"
      type: "string"
      immutable: false
      required: true
      options:
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"
      - label: "IfNotPresent"
        value: "IfNotPresent" 
  pullSecret:
    __metadata:
      label: "Image pull secret"
      description: "Secret to use when pulling the image.  Set this when using an image from a private registry"
      type: "string"
      required: false

## Arch metadata
arch:
  __metadata:
    label: "Architecture scheduling preferences"
  amd64:
    __metadata:
      name: "amd64"
      label: "amd64"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No Preference"
        value: "2 - No Preference"  
      - label: "3 - Most preferred"
        value: "3 - Most preferred"  
  
  ppc64le:
    __metadata:
      name: "ppc64le"
      label: "ppc64le scheduling preference"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No Preference"
        value: "2 - No Preference"  
      - label: "3 - Most preferred"
        value: "3 - Most preferred"  
  
  s390x:
    __metadata:
      name: "s390x"
      label: "s390x scheduling preference"
      description: "Architecture preference for target worker node."
      type: "string"
      immutable: false
      required: true
      options:
      - label: "0 - Do not use"
        value: "0 - Do not use"
      - label: "1 - Least preferred"
        value: "1 - Least preferred"
      - label: "2 - No Preference"
        value: "2 - No Preference"  
      - label: "3 - Most preferred"
        value: "3 - Most preferred"  

## global persistence parameters
persistence:
  __metadata:
    label: "Persistence"
  enabled:
    __metadata:
      label: "Enable persistence"
      description: "Whether or not to store MQ messages and configuration on a Persistent Volume"
      type: "boolean"
      required: true
  useDynamicProvisioning:
    __metadata:
      label: "Use dynamic provisioning"
      description: "Whether or not to use Storage Classes to provision a Persisent Volume automatically"
      type: "boolean"
      required: true

dataPVC:
  __metadata:
    label: "Data PVC"
  name:
    __metadata:
      label: "Name"
      description: "Name of Persistent Volume Claim, used for MQ objects and messages"
      type: "string"
      required: true
  storageClassName:
    __metadata:
      label: "Storage Class name"
      description: "Storage class of Persistent Volume Claim, used for MQ objects and messages"
      type: "string"
      required: false
  size:
    __metadata:
      label: "Size"
      description: "Size of Persistent Volume Claim, used for MQ objects and messages"
      type: "string"
      required: true

service:
  __metadata:
    label: "Service"
  name:
    __metadata:
      label: "Service name"
      description: "Service name"
      type: "string"
      required: true
  type:
    __metadata:
      label: "Service type"
      description: "Type of service"
      type: "string"
      required: true
      options:
      - label: "ClusterIP"
        value: "ClusterIP"
      - label: "NodePort"
        value: "NodePort"
      - label: "LoadBalancer"
        value: "LoadBalancer" 
      - label: "ExternalName"
        value: "ExternalName" 

resources:
  __metadata:
    label: "Resources"
  requests:
    cpu: 
      __metadata: 
        label: "CPU request"
        description: "The requested CPU"
        type: "string"
        required: true   
    memory: 
      __metadata: 
        label: "Memory request"
        description: "The requested memory"
        type: "string"
        required: true   
  limits:
    cpu: 
      __metadata: 
        label: "CPU limit"
        description: "The CPU limit"
        type: "string"
        required: true
    memory: 
      __metadata: 
        label: "Memory limit"
        description: "The memory limit"
        type: "string"
        required: true

queueManager:
  __metadata:
    label: "Queue manager"
  name:
    __metadata:
      label: "Queue manager name"
      description: "MQ queue manager name, which defaults to the Helm release name"
      type: "string"
      required: false
  dev:
    __metadata:
      label: "Default Developer Configuration"
      description: "Configure some queue manager basics, suitable for developer use"
    adminPassword:
      __metadata:
        label: "Admin password"
        description: "Password for 'admin' user"
        type: "password"
        required: false
    appPassword:
      __metadata:
        label: "App password"
        description: "Password for 'app' user to use for messaging"
        type: "password"
        required: false

nameOverride:
  __metadata:
    label: "Name override"
    description: "This can be set to partially override the name of the resources created by this chart"
    type: "string"
    required: false

# log section specifies settings for MQ error logs
log:
  __metadata:
    label: "Log"
  format:
    __metadata:
      label: "Error log format"
      description: "The format of container logs (MQ error logs) output to the container's console"
      type: "string"
      required: false
      options:
      - label: "JSON"
        value: "json"
      - label: "Basic"
        value: "basic"